### PR TITLE
Correct iPhone 14 width

### PR DESCRIPTION
**Pull request by RyanRoberts**
Corrected the iPhone 14 width from 320 to 390.

Thanks

### CODE REVIEW

**Comment by ghost** [comment]
Hey @RyanRoberts,
Thanks for your contribution. If you have any references please add them to this pull request.

**Comment by RyanRoberts** [comment]
Sorry, what do you mean by references?

**Comment by ghost** [comment]
> Sorry, what do you mean by references?



> Sorry, what do you mean by references?

https://yesviz.com/iphones.php

**Review by ghost — APPROVED** [review]

**Comment by RyanRoberts** [comment]
If you scroll to Display on https://www.apple.com/uk/iphone-14/specs/ you'll see it's 2532x1170 so 1170 / 3 is 390 pixels. Another reference here https://blisk.io/devices/details/iphone-14

**Pull request merged**
